# https://taskfile.dev

version: '3'

vars:
  GUTENBERG: https://www.gutenberg.org/cache/epub/feeds/pg_catalog.csv
  GBFETCH: https://www.gutenberg.org/ebooks/
  GBEXT: .txt.utf-8
  OUTPUT_DIR: output
tasks:
  default:
    cmds:
      - task $(cat Taskfile.yml | yq '.tasks | keys.[]' | fzf)
    silent: true
  search:
    cmds:
      - ./bin/fzgrep cat 'pg_catalog.csv' | awk -F, '{print $6"-"$4}'
      #- cat 'pg_catalog.csv' | fzf | awk -F, '{print $6"-"$4}'
  fetch:
    cmds:
      - ./bin/fzgrep cat 'pg_catalog.csv' | awk -F, '{print "{{.GBFETCH}}"$1"{{.GBEXT}} -O {{.OUTPUT_DIR}}/"$1".txt"}' | xargs wget -w 2 -m -H 
      #- cat 'pg_catalog.csv' | fzf | awk -F, '{print "{{.GBFETCH}}"$1"{{.GBEXT}} -O {{.OUTPUT_DIR}}/"$1".txt"}' | xargs wget -w 2 -m -H 
  convert2yaml:
    cmds:
      - yq -oy pg_catalog.csv > pg.yaml # converts the csv file to yaml for faster parsing
  repo:
    cmds:
      - curl {{.GUTENBERG}} -o pg_catalog.csv
  exit:
    cmds:
      - exit
